version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 99
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: increase
    commit-message:
      prefix: fix
      prefix-development: build
      include: scope
    ignore:
      - dependency-name: "chai"
        versions: [">=5.0"] # ESM only
    reviewers:
      - "Brightspace/lurvig"
