version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 99
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: fix
      prefix-development: build
      include: scope
    ignore:
      - dependency-name: "chai"
        versions: [">=5.0"] # ESM only
      - dependency-name: "eslint"
        versions: [">=9.0"]
      - dependency-name: "eslint-config-brightspace"
        versions: [">=2.0"] # Requires eslint >= 9
      - dependency-name: "eslint-plugin-mocha"
        versions: [">=11.0"] # ESM only
      # update-package-lock workflow already handles most minor/patch updates
      # continue checking minor updates to cover dependendencies with version pattern 0.*.*
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
